# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor: !include sensor.yaml
camera: !include cameras.yaml

frontend: !include themes.yaml
template: !include sidebar.yaml


lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home-Code
      icon: mdi:code-braces-box
      show_in_sidebar: true
      filename: kwok-lovelace.yaml