kiosk_mode:
  hide_header: true
  hide_sidebar: true
views:
  - theme: Backend-selected
    title: 所有设备
    path: light
    icon: mdi:cellphone-link
    type: panel
    badges: []
    cards:
      - type: picture-elements
        image: /local/ui/sidebar_background.png
        elements:
          - enableColumns: true
            rows:
              - columns:
                  - column: 1
                    entities:
                      - entities:
                          - entity: light.yeelink_ceiling1_bb86_light
                            icon: mdi:ceiling-light
                          - entity: media_player.xiaomi_s12_2e82_play_control
                            icon: mdi:speaker
                          - entity: climate.lumi_v2_c5cc_air_conditioner
                            icon: mdi:toggle-switch-off
                          - entity: switch.zhimi_m1_34c8_switch_status
                            icon: mdi:air-conditioner
                          - entity: switch.chuangmi_039a01_ce28_switch_status
                            icon: mdi:webcam
                        title: 卧室
                    tileOnRow: 5
                  - column: 1
                    entities:
                      - entities:
                          - entity: light.yeelink_ceiling1_bb86_light
                            icon: mdi:ceiling-light
                        title: 主卫
                    tileOnRow: 1
                row: 1
            statePositionTop: true
            style:
              height: 100%
              left: 60%
              top: 50%
              width: 85%
            type: custom:homekit-card

          - action: none
            image: /local/ui/sidebar_light_on.png
            style:
              left: 8.8%
              top: 37.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/light
            hold_action:
              action: none
            type: image
          - action: none
            image: /local/ui/sidebar_va_off.png
            style:
              left: 8.8%
              top: 44.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/robot
            hold_action:
              action: none
            type: image

          - color_thresholds:
              - color: '#4dd2ff'
                value: 17
              - color: '#01a4db'
                value: 20
              - color: '#fccd68'
                value: 23
              - color: '#fd8524'
                value: 26
              - color: '#ff1a1a'
                value: 30
            entities:
              - sensor.living_binary_temperature
              - sensor.airhumidifier_temperature
            icon: mdi:home-thermometer-outline
            update_interval: 600
            show:
              icon: true
              legend: false
              name: false
            style: |
              :host {
               left: 8.6%;
               top:  74%;
               width: 17.5%;
               overflow: hidden;
               height: 15%;
               background: none  !important;
               box-shadow: none !important;
              }
              .header {
               font-size: 10%;
               position: absolute !important;
               width: 5% !important;
               padding: 0 !important;
               right: 20% !important;
               top: 15% !important;
              }
              ha-card {
               background: none  !important;
               padding: 0 !important;
              }
              .icon > ha-icon {
               width:10% !important;
               height:10% !important;
              }
              .state__time{
               font-size:0.9vw !important;
               margin-top: 0.2vw;
               font-weight: 300 !important;
               opacity: 0.4 !important;
              }
              .states {
               font-size: 100% !important;
               padding: 1vw 0vw 0vw 0vw  !important;
               margin: auto !important;
               width: 68%;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:mini-graph-card
          - backdrop: false
            entity: weather.adelaide
            name: ' '
            style: |
              :host {
              left: 8.4%;
              top:  20.5%;
              width: 13%;
              height: 6% !important;
              overflow: hidden;
              height: 11%;
              background: none  !important;
              box-shadow: none !important;
              font-size: 100% !important;
              }
              ha-card {
              background: none  !important;
              box-shadow: none !important;
              flex-flow: row-reverse !important;
              padding: 0 !important;
              }
              .weather__info--add{
              display : none !important;
              }
              .weather__info{
              flex-grow: 1;
              min-height: 0 !important;
              height: 5%;
              margin-left: 2%;
              }
              .weather__icon{
              margin-right:0.5% !important;
              margin-top: -3%;
              width: 2vw !important;
              height: 2vw !important;
              flex: 0 0 2vw !important;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:simple-weather-card
          - entity: sensor.time
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.7)
              font-size: 400%
              font-weight: 400
              left: 1.5%
              letter-spacing: '-0.05vw'
              max-width: 1px
              top: 8%
            tap_action:
              action: none
            type: state-label
          - entity: sensor.date_string
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.3)
              font-size: 1.3vw
              font-weight: 300
              left: 16.9%
              letter-spacing: 0.05vw
              text-align: left
              top: 14%
              width: 30%
            tap_action:
              action: none
            type: state-label
  
  - theme: Backend-selected
    title: 扫地机
    path: robot
    icon: mdi:robot-vacuum
    type: panel
    badges: []
    cards:
      - type: picture-elements
        image: /local/ui/sidebar_backgroud.png
        elements:

          - type: custom:xiaomi-vacuum-map-card
            entity: vacuum.rockrobo_v1_5f71_robot_cleaner
            map_source:
              camera: camera.xiaomi_cloud_map_extractor
            calibration_source:
              camera: true
            language: zh

            style: |
              :host {
                left: 58.5%;
                top:  50%;
                width: 50%;
                overflow: hidden;
                height: 100%;
                background: none !important;
                box-shadow: none !important;

          - action: none
            image: /local/ui/sidebar_light_off.png
            style:
              left: 8.8%
              top: 37.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/light
            hold_action:
              action: none
            type: image
          - action: none
            image: /local/ui/sidebar_va_on.png
            style:
              left: 8.8%
              top: 44.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/robot
            hold_action:
              action: none
            type: image

          - color_thresholds:
              - color: '#4dd2ff'
                value: 17
              - color: '#01a4db'
                value: 20
              - color: '#fccd68'
                value: 23
              - color: '#fd8524'
                value: 26
              - color: '#ff1a1a'
                value: 30
            entities:
              - sensor.living_binary_temperature
              - sensor.airhumidifier_temperature
            icon: mdi:home-thermometer-outline
            update_interval: 600
            show:
              icon: true
              legend: false
              name: false
            style: |
              :host {
               left: 8.6%;
               top:  74%;
               width: 17.5%;
               overflow: hidden;
               height: 15%;
               background: none  !important;
               box-shadow: none !important;
              }
              .header {
               font-size: 10%;
               position: absolute !important;
               width: 5% !important;
               padding: 0 !important;
               right: 20% !important;
               top: 15% !important;
              }
              ha-card {
               background: none  !important;
               padding: 0 !important;
              }
              .icon > ha-icon {
               width:10% !important;
               height:10% !important;
              }
              .state__time{
               font-size:0.9vw !important;
               margin-top: 0.2vw;
               font-weight: 300 !important;
               opacity: 0.4 !important;
              }
              .states {
               font-size: 100% !important;
               padding: 1vw 0vw 0vw 0vw  !important;
               margin: auto !important;
               width: 68%;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:mini-graph-card
          - backdrop: false
            entity: weather.adelaide
            name: ' '
            style: |
              :host {
              left: 8.4%;
              top:  20.5%;
              width: 13%;
              height: 6% !important;
              overflow: hidden;
              height: 11%;
              background: none  !important;
              box-shadow: none !important;
              font-size: 100% !important;
              }
              ha-card {
              background: none  !important;
              box-shadow: none !important;
              flex-flow: row-reverse !important;
              padding: 0 !important;
              }
              .weather__info--add{
              display : none !important;
              }
              .weather__info{
              flex-grow: 1;
              min-height: 0 !important;
              height: 5%;
              margin-left: 2%;
              }
              .weather__icon{
              margin-right:0.5% !important;
              margin-top: -3%;
              width: 2vw !important;
              height: 2vw !important;
              flex: 0 0 2vw !important;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:simple-weather-card
          - entity: sensor.time
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.7)
              font-size: 400%
              font-weight: 400
              left: 1.5%
              letter-spacing: '-0.05vw'
              max-width: 1px
              top: 8%
            tap_action:
              action: none
            type: state-label
          - entity: sensor.date_string
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.3)
              font-size: 1.3vw
              font-weight: 300
              left: 16.9%
              letter-spacing: 0.05vw
              text-align: left
              top: 14%
              width: 30%
            tap_action:
              action: none
            type: state-label

  - theme: Backend-selected
    title: 天气预报
    path: weather
    icon: mdi:weather-cloudy
    type: panel
    badges: []
    cards:
      - type: picture-elements
        image: /local/ui/sidebar_background.png
        elements:
          - current: true
            details: true
            entity: weather.adelaide
            forecast: true
            name: 天气预报
            style: |
              :host {
                left: 58.5%;
                top:  38%;
                width: 77%;
                overflow: hidden;
                height: 63%;
                background: none !important;
                box-shadow: none !important;
              }
              .current {
                margin-bottom: 7vw;
              }
              .variations {
                margin-bottom: 4vw;
              }
              ha-card {
                height: 100%;
                background: none  !important;
                box-shadow: none !important;
                border-radius: 1vw;
                font-size: 1.2vw !important;
              }
              .forecast{
                padding: 0 2.5%;
                width: 95%;
              }
              .forecast .day:first-child{
                border-left: 0.1em solid #d9d9d9;
              }
              .forecast .day:last-child{
                border-right: 0.1em solid #d9d9d9;
              }
            type: 'custom:weather-card'


          - action: none
            image: /local/ui/sidebar_light_off.png
            style:
              left: 8.8%
              top: 37.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/light
            hold_action:
              action: none
            type: image
          - action: none
            image: /local/ui/sidebar_va_off.png
            style:
              left: 8.8%
              top: 44.6%
              width: 14.9%
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/robot
            hold_action:
              action: none
            type: image


          - color_thresholds:
              - color: '#4dd2ff'
                value: 17
              - color: '#01a4db'
                value: 20
              - color: '#fccd68'
                value: 23
              - color: '#fd8524'
                value: 26
              - color: '#ff1a1a'
                value: 30
            entities:
              - sensor.living_binary_temperature
              - sensor.airhumidifier_temperature
            icon: mdi:home-thermometer-outline
            update_interval: 600
            show:
              icon: true
              legend: false
              name: false
            style: |
              :host {
               left: 8.6%;
               top:  74%;
               width: 17.5%;
               overflow: hidden;
               height: 15%;
               background: none  !important;
               box-shadow: none !important;
              }
              .header {
               font-size: 10%;
               position: absolute !important;
               width: 5% !important;
               padding: 0 !important;
               right: 20% !important;
               top: 15% !important;
              }
              ha-card {
               background: none  !important;
               padding: 0 !important;
              }
              .icon > ha-icon {
               width:10% !important;
               height:10% !important;
              }
              .state__time{
               font-size:0.9vw !important;
               margin-top: 0.2vw;
               font-weight: 300 !important;
               opacity: 0.4 !important;
              }
              .states {
               font-size: 100% !important;
               padding: 1vw 0vw 0vw 0vw  !important;
               margin: auto !important;
               width: 68%;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:mini-graph-card
          - backdrop: false
            entity: weather.adelaide
            name: ' '
            style: |
              :host {
              left: 8.4%;
              top:  20.5%;
              width: 13%;
              height: 6% !important;
              overflow: hidden;
              height: 11%;
              background: none  !important;
              box-shadow: none !important;
              font-size: 100% !important;
              }
              ha-card {
              background: none  !important;
              box-shadow: none !important;
              flex-flow: row-reverse !important;
              padding: 0 !important;
              }
              .weather__info--add{
              display : none !important;
              }
              .weather__info{
              flex-grow: 1;
              min-height: 0 !important;
              height: 5%;
              margin-left: 2%;
              }
              .weather__icon{
              margin-right:0.5% !important;
              margin-top: -3%;
              width: 2vw !important;
              height: 2vw !important;
              flex: 0 0 2vw !important;
              }
            tap_action:
              action: navigate
              navigation_path: /lovelace-floor/weather
            type: custom:simple-weather-card
          - entity: sensor.time
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.7)
              font-size: 400%
              font-weight: 400
              left: 1.5%
              letter-spacing: '-0.05vw'
              max-width: 1px
              top: 8%
            tap_action:
              action: none
            type: state-label
          - entity: sensor.date_string
            hold_action:
              action: none
            style:
              color: rgba(255, 255, 255, 0.3)
              font-size: 1.3vw
              font-weight: 300
              left: 16.9%
              letter-spacing: 0.05vw
              text-align: left
              top: 14%
              width: 30%
            tap_action:
              action: none
            type: state-label
 
